Modifies pre-commit checks. -- SGPROJ-1600
StratusGrid/terraform-aws-anomaly-detection-alerts pull request #6
Opened 2022-10-03 16:36 UTC by DJKaswa

## Change description

> Removed unnecessary files, and adds tfenv to track terraform version and install it automatically with tfenv.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

2022-10-19 08:43 UTC, JoseMotto-sg requested changes

2022-10-19 08:43 UTC, JoseMotto-sg commented on .github/workflows/pre-commit.yml
> +    secrets: inherit
Delete this
```suggestion
    secrets: inherit
```

2022-10-19 08:43 UTC, JoseMotto-sg commented on .terraform-version
> +1.2.8
```suggestion
1.3.0
```

2022-10-25 19:41 UTC, DJKaswa commented
@JoseMotto-sg please review my response to your suggestions/changes requested. Other than that, we should be ready to merge this.

2022-10-26 10:08 UTC, JoseMotto-sg approved these changes
LGTM

2022-10-26 19:36 UTC, merged